matrix:
  include:
    - os: osx
      osx_image: xcode11.6
      env:
        - MATRIX_EVAL="CC=gcc-11.0.3 && CXX=g++-11.0.3"

before_install:
    - eval "${MATRIX_EVAL}"
    - git clone https://github.com/libcheck/check.git
    - cd check
    - autoreconf --install
    - ./configure
    - make
    - make install
    - cd ..
script:
  - make
  - make test
