matrix:
  include:
    - os: osx
      osx_image: xcode11.6
      env:
        - MATRIX_EVAL="CC=gcc-11.0.3 && CXX=g++-11.0.3"

before_install:
    - eval "${MATRIX_EVAL}"
script:
  - make
#  - make test
